add_newline=false

[character]
error_symbol = "[â¯](bold red)"
success_symbol = "[â¯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"


[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[[battery.display]]
threshold = 20
style = "bold blue"

[lua]
symbol = "[î˜ ](bold yellow)"

[python]
symbol = "[î˜† ](bold #64648c)"
style = "bold #64648c"
