add_newline=false

[character]
error_symbol = "[â¯](bold #ff5555)"
success_symbol = "[â¯](bold #50fa7b)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "bold #50fa7b"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[[battery.display]]
threshold = 20
style = "bold blue"

[lua]
symbol = "[î˜ ](bold yellow)"

[python]
symbol = "[î˜† ](bold #64648c)"
style = "bold #64648c"

[aws]
style = "bold #ffb86c"

[cmd_duration]
style = "bold #f1fa8c"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
